config_name: "Dyode test"
config_version : 1.0
config_date: 2023-08-09

dyode_in:
  ip: 10.0.1.1
  mac: 00:e0:4c:22:47:76
dyode_out:
  ip: 10.0.1.2
  mac: 00:e0:4c:22:47:26

modules:
  "Fileshare":
     type: folder
     port: 9600
     in: /home/toor/in
     out: /home/toor/out